version: "3.9"
services:
  redis:
    image: redis:7.0.5
    restart: always
    ports:
      - "6380:6379"
    volumes: 
      - redis:/data
  postgres:
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes: 
      - postgres:/data
      - /var/run/postgresql:/var/run/postgresql
volumes:
  redis:
    driver: local
  postgres:
    driver: local